var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;for(c=c||0;c<e;c++)if(b[c]==a||Object.is(b[c],a))return!0;return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
$(document).ready(function(){mobile=isMobileDevice();detectURLparams();mobile&&$(".map_titles").addClass("map_titles_mob");displayInfo(null,noinfo);generateButtons()});var mobile=!1,startX,startY,baketrix={},onceLoaded,poly_fills=["howmany","roomprice","entireprice","room365usage","entire365usage"],map_method="area",current_area,markerClusterer,mapo,defaultLocation={lat:55.959720608,lng:-3.189344969},mlist,userCircle,showURL="https://psirens.github.io/airbnb-edb/",noinfo=!1;
function setupDataset(a,b){if(document.URL&&(-1==document.URL.indexOf("127.0.0.1:8080")&&-1==document.URL.indexOf("192.168.0.2")&&-1==document.URL.indexOf("psirens")||-1==document.URL.indexOf("airbnb-edb")))return!1;current_area=null;null!=mapo&&(clearPolyAreas(),mapo.clearMarkers());cleanListingData(a,function(){cleanAreaData();generateAreaPolys("howmany");if(null!=onceLoaded){if("host"==onceLoaded.type&&(baketrix.hosts[onceLoaded.value]||baketrix.singlehosts[onceLoaded.value]))mapo.clearMarkers(),
generateHostPins({host_id:onceLoaded.value});else if("area"==onceLoaded.type){var a=isAnArea(onceLoaded.value);a&&(map_method=onceLoaded.type,current_area=a,redoSearch())}else if("find"==onceLoaded.type&&""!=onceLoaded.value){a=onceLoaded.value;var b=a.split(",");a=b[0];b=b[1];map_method=onceLoaded.type;displayUserPosition(a,b);findListingsInUserCircle();mapFitBounds(!0)}else"search"==onceLoaded.type&&""!=onceLoaded.value?(a=onceLoaded.value,$("#search_listings").val(a),searchListings()):"listing"==
onceLoaded.type&&baketrix.listings[onceLoaded.value]&&createPin(onceLoaded.value)&&(showMarkerDetails(onceLoaded.value,!0,"green"),mapFitBound(onceLoaded.value));onceLoaded=null}})}function clearPolyAreas(){$.each(baketrix.areas,function(a,b){null!=baketrix.areas[a].poly&&mapo.clearPolyArea(baketrix.areas[a].poly)})}
function cleanListingData(a,b){baketrix={listings:{},type:{entire:[],room:[]},thisyear:[],isavailable:[],isavailablefringe:[],isavailableroy:[],aug_reviews:[],areas:{},hosts:{},singlehosts:{},prolific_entire_hosts:{}};$.getJSON(sroot+a,function(a){if(1<a.listings.length&&null!=a.listings[0].id){var c={};$.each(a.listings,function(a,b){c[b.id]=b;delete c[b.id].id});baketrix.listings=c}else baketrix.listings=a.listings;var e=0;$.each(baketrix.listings,function(a,b){a=parseInt(a);"Entire home/apt"==
b.room_type?baketrix.type.entire.push(a):baketrix.type.room.push(a);null==baketrix.singlehosts[b.host_id]&&(baketrix.singlehosts[b.host_id]=[]);baketrix.singlehosts[b.host_id].push(a);null==baketrix.hosts[b.host_id]&&(baketrix.hosts[b.host_id]=[]);null==baketrix.areas[b.neighbourhood]&&(baketrix.areas[b.neighbourhood]={list:[]});(0<getAvail(b.availability)||0<getAvail(b.availability,!0))&&baketrix.isavailable.push(a);0<getAvail(b.availability,!0)&&baketrix.isavailablefringe.push(a);null!=b.aug_reviews&&
""!=b.aug_reviews&&0<parseInt(b.aug_reviews)&&baketrix.aug_reviews.push(a);var c=(new Date).getFullYear();if(null!=b.last_review&&""!=b.last_review){var d=parseInt(b.last_review.substring(0,4));d!=c&&d!=c-1||baketrix.thisyear.push(a)}else e++;baketrix.areas[b.neighbourhood].list.push(a);baketrix.hosts[b.host_id].push(a)});b();console.log("ccnulls = "+e)}).fail(function(a){console.log(a)})}
function getPrice(a,b,c){return(c=void 0===c?!1:c)?a[c]:(void 0===b?0:b)?-1==a.true_aug?a.jan_avg_aug:a.true_aug:a.jan_avg_roy||a.true_roy?-1==a.true_roy?a.jan_avg_roy:a.true_roy:parseFloat(a.price)}function getAvail(a,b,c){return(c=void 0===c?!1:c)?a[c]:(void 0===b?0:b)?-1==a.true_aug?a.aug:a.true_aug:a.true_roy||a.roy?-1==a.true_roy?a.roy:a.true_roy:a["365"]}
function cleanAreaData(){var a=baketrix.areas;$.each(a,function(b,c){a[b].entire=0;a[b].room=0;a[b].year=0;a[b].available=0;a[b].roomprice=0;a[b].entireprice=0;a[b].roomavailindex=0;a[b].entireavailindex=0;a[b].reviews_per_month_entire=0;a[b].reviews_per_month_room=0;var d=(new Date).getFullYear();$.each(c.list,function(c,f){null!=baketrix.listings[f]?(c=getPrice(baketrix.listings[f].prices),"Entire home/apt"==baketrix.listings[f].room_type?(a[b].entire++,a[b].entireprice+=c,a[b].entireavailindex+=
getAvail(baketrix.listings[f].availability),a[b].reviews_per_month_entire+=parseFloat(""!=baketrix.listings[f].reviews_per_month?baketrix.listings[f].reviews_per_month:0)):(a[b].room++,a[b].roomprice+=c,a[b].roomavailindex+=getAvail(baketrix.listings[f].availability),a[b].reviews_per_month_room+=parseFloat(""!=baketrix.listings[f].reviews_per_month?baketrix.listings[f].reviews_per_month:0)),0<getAvail(baketrix.listings[f].availability)&&a[b].available++,c=parseInt(baketrix.listings[f].last_review.substring(0,
4)),null==baketrix.listings[f].last_review||""==baketrix.listings[f].last_review||c!=d&&c!=d-1||a[b].year++):console.log("err no listing? "+f)});a[b].entireprice=(a[b].entireprice/a[b].entire).toFixed(2);a[b].roomprice=(a[b].roomprice/a[b].room).toFixed(2);a[b].reviews_per_month_entire=a[b].reviews_per_month_entire.toFixed(2);a[b].reviews_per_month_room=a[b].reviews_per_month_room.toFixed(2);a[b].roomavailindex=(a[b].roomavailindex/(3.65*a[b].room)).toFixed(2);a[b].entireavailindex=(a[b].entireavailindex/
(3.65*a[b].entire)).toFixed(2)});baketrix.areas=a}function GetMap(){mapo=new BingMap("#map",defaultLocation,this);setupDataset("jan_listings.json")}function initMap(){mapo=new GoogMap(document.getElementById("map"),defaultLocation,this);setupDataset("jan_listings.json")}function getURLParameter(a){return decodeURIComponent(((new RegExp("[?|&]"+a+"=([^&;]+?)(&|#|;|$)")).exec(location.search)||[null,""])[1].replace(/\+/g,"%20"))||null}
function detectURLparams(){var a=getURLParameter("host"),b=getURLParameter("room"),c=getURLParameter("area"),d=getURLParameter("loc"),e=getURLParameter("search"),f=getURLParameter("noi");null!=a?onceLoaded={type:"host",value:a}:null!=b?onceLoaded={type:"listing",value:b}:null!=c?onceLoaded={type:"area",value:c}:null!=d?onceLoaded={type:"find",value:d}:null!=e&&(onceLoaded={type:"search",value:e});null!=f&&(noinfo=!0)}
function isAnArea(a){var b=Object.keys(baketrix.areas);return b.length>a&&null!=b[a]?b[a]:!1}function findWhichArea(a,b){var c=null;$.each(baketrix.areas,function(d,e){if(null!=e.poly&&mapo.polyContains(e.poly,a,b))return console.log("you are within: "+d),c=d});return c}function displayUserPosition(a,b){mapo.createUserCircle(a,b)&&$("#button_find_nearme").removeClass("hidden")}function updateUserCircle(a){mapo.updateUserCircleLocation(a);findListingsInUserCircle();mapFitBounds(!0)}
function findListingsInUserCircle(){if(null!=mapo.userCircle){mapo.clearMarkers();var a=mapo.userCircleBounds();mlist=[];displayBreadcrumb("Drag <a href='"+showURL+"?noi=1&loc="+(a.sw.lat+a.ne.lat)/2+","+(a.sw.lng+a.ne.lng)/2+"' target='_blank'>user marker</a>, untick Cluster or zoom to see more");$.each(baketrix.listings,function(b,d){b=parseInt(b);baketrix.listings[b].latitude>=a.sw.lat&&baketrix.listings[b].latitude<=a.ne.lat&&baketrix.listings[b].longitude>=a.sw.lng&&baketrix.listings[b].longitude<=
a.ne.lng&&mlist.push(b)});mlist=splitListOnFilters(mlist,getMapType(),"summary").list;$("#map_details").html("");var b=[];$.each(mlist,function(a,d){if(a=createPin(d))b.push(a),showMarkerDetails(d)});mapo.createAndAddPins(b,$("#cluster_option").is(":checked"));0<Object.keys(mlist).length?mapFitBounds():noResultsMessage("near you")}}function displayBreadcrumb(a){var b=$("#results_breadcrumb");b.removeClass("hidden");b.html(a)}
function generateButtons(){doClick($("#ddisc"),function(a){$(".disclaimer").toggleClass("hidden")});doClick($("#button_find_me"),function(a){"geolocation"in navigator?(map_method="find",navigator.geolocation.getCurrentPosition(function(a){mapo.withinBounds(a.coords.latitude,a.coords.longitude)?displayUserPosition(a.coords.latitude,a.coords.longitude):displayUserPosition(defaultLocation.lat,defaultLocation.lng);findListingsInUserCircle();mapFitBounds(!0)},function(a){console.log(a);console.log("we couldn't find you.. move the circle to find Airbnbs in the vicinity");
displayUserPosition(defaultLocation.lat,defaultLocation.lng);findListingsInUserCircle();mapFitBounds(!0)})):(displayUserPosition(defaultLocation.lat,defaultLocation.lng),findListingsInUserCircle(),mapFitBounds(!0))});doClick($("#button_info"),displayInfo);doClick($("#button_search"),searchListings);$("#map_polyfill").change(function(){generateAreaPolys($(this).val())});doClick($("#most_largest"),function(){showMostBedrooms()});doClick($("#most_expensive"),function(){showMostExpensive()});doClick($("#most_used"),
function(){showMostPopular()});doClick($("#most_profitable"),function(){showMostProfitable()});$("#cluster_option").on("change",function(a){mapo.setCluster($(this).is(":checked"))});$("#weight_option").on("change",function(a){generateHeatMap()});$("#dataset").on("change",function(a){setupDataset($(this).val(),!0)});$("#map_method").on("change",function(a){a=$(this).val();"all"==a?($("#weight_map").addClass("hidden"),drawAllAreas()):"area"==a?(mapo.clearHeatLayer(),mapo.clearMarkers(),generateAreaPolys("howmany"),
$("#map_details").html(""),$("#weight_map").addClass("hidden"),map_method="area"):(mapo.clearMarkers(),clearPolyAreas(),$("#map_details").html(""),$("#weight_map").removeClass("hidden"),map_method="heat",generateHeatMap())});doClick($("#button_prolific_hosts"),function(a){if(!$("#prolific_hosts_container").is(":visible")){var b="";if(null==baketrix.prolific_entire_hosts||0==Object.keys(baketrix.prolific_entire_hosts).length)baketrix.prolific_entire_hosts=findProlificHosts("entire");var c=0;$.each(baketrix.prolific_entire_hosts,
function(a,e){$.each(e,function(d,e){b="<div class='col-3 phost' data-host='"+e+"'>"+getHostName(e)+" (#"+a+")</div>"+b;c++})});b="<div class='col-2'><button id='button_close_prolific' onclick='closeProlific();'>&lt; Back</button></div><div class='col-10 clickable'><div class='row '>"+b+"</div></div>";$("#prolific_hosts_content").html(b);$("#mapoptions").addClass("hidden");$("#prolific_hosts_container").removeClass("hidden")}});doClick($("#prolific_hosts_content"),function(a){"button_close_prolific"==
a.target.id?closeProlific():a.target.hasAttribute("data-host")&&(mapo.clearMarkers(),generateHostPins({host_id:a.target.attributes.getNamedItem("data-host").value}))});$(".search_box").change(function(a){if("checkbox_available_fringe"==this.id){a="Price";var b="Avail days",c="Reviews /month";$("#checkbox_available_fringe").is(":checked")&&(a="Price Fringe",b="Avail Fringe",c="Reviews Aug");$("#heading_price").html(a);$("#heading_avail").html(b);$("#heading_reviewrate").html(c)}redoSearch()});doClick($("#map_details"),
function(a){a=$(a.target);if(null!=a)if(a.hasClass("host_name")){mapo.clearMarkers();var b=a.parent().attr("id");a=b.substring(4);b=baketrix.listings[a];b.id=a;generateHostPins(b)}else a.hasClass("findinmap")&&(b=a.parent().attr("id"),null!=highlightedRow&&$(highlightedRow).removeClass("highlighted"),highlightedRow=a.parent(),highlightedRow.addClass("highlighted"),a=b.substring(4),mapFitBound(a))})}
function redoSearch(){"area"==map_method?current_area?(generateAreaPinCluster(current_area,!0),mapFitBounds(!1),generateAreaPolys($("#map_polyfill").val())):($("#map_details").html(""),mapo.clearMarkers(),mlist=null):"host"==map_method?(mapo.clearMarkers(),generateHostPins({host_id:current_area}),generateAreaPolys($("#map_polyfill").val())):"heat"==map_method?generateHeatMap():"find"==map_method?findListingsInUserCircle():"all"==map_method?drawAllAreas():"search"==map_method&&searchListings()}
function populateMlist(a){a=void 0===a?!1:a;console.log("artificially populate mlist");if(a||null==mlist&&("heat"==map_method||"search"==map_method||"area"==map_method&&null==current_area))mlist=splitListOnFilters(Object.keys(baketrix.listings).map(Number),getMapType()).list}
function searchListings(){var a=$("#search_listings").val();if(null!=a&&""!=a&&2<a.length){a=a.toLowerCase();map_method="search";populateMlist(!0);var b=mlist;mapo.clearMarkers();var c=[];$.each(baketrix.listings,function(b,d){var e=d.name.toLowerCase(),f=d.host_name.toLowerCase();-1<e.indexOf(a)?c.push(parseInt(b)):-1<f.indexOf(a)?c.push(parseInt(b)):(-1<d.host_id.indexOf(a)||-1<b.indexOf(a))&&c.push(parseInt(b))});c=b.filter(function(a){return c.includes(a)});b=c.length;mlist=c;$("#map_details").html("");
var d=[];$.each(mlist,function(a,b){if(a=createPin(b))d.push(a),showMarkerDetails(b)});mapo.createAndAddPins(d,$("#cluster_option").is(":checked"));0<Object.keys(mlist).length?(mapFitBounds(),displayBreadcrumb(b+" results for <a href='"+showURL+"?search="+a+"&noi=1' target='_blank'>"+a+"</a>")):noResultsMessage("No filtered results for "+a)}}
function splitHighlightColumns(a,b,c){$("#heading_type").toggleClass("search_border",a);$("#heading_avail").toggleClass("search_border",b);$("#heading_lastreview").toggleClass("search_border",c)}
function splitListOnFilters(a,b,c){c=void 0===c?!1:c;if(null==c||0==c)c="none";if(null!=a){var d=Object.keys(a).length,e=!1;if("both"!=b){a=a.filter(function(a){return baketrix.type[b].includes(a)});if("entire"==b){var f=Object.keys(a).length;var g=d-f}else g=Object.keys(a).length,f=d-g;e=!0}var h=!1,k=!1;if($("#checkbox_lastbooked").is(":checked")){a=a.filter(function(a){return baketrix.thisyear.includes(a)});var l=a.length;h=!0}if($("#checkbox_available").is(":checked")){a=a.filter(function(a){return baketrix.isavailable.includes(a)});
var m=a.length;k=!0}if($("#checkbox_available_fringe").is(":checked")){if(k||!k&&!h)a=a.filter(function(a){return baketrix.isavailablefringe.includes(a)});if(h||!k&&!h)a=a.filter(function(a){return baketrix.aug_reviews.includes(a)});k||h||(h=k=!0)}splitHighlightColumns(e,k,h);if("summary"==c){if(null==f||null==g||null==l||null==m){f=null==f?0:f;g=null==g?0:g;l=null==l?0:l;m=null==m?0:m;var p=!$("#checkbox_lastbooked").is(":checked"),q=!$("#checkbox_available").is(":checked"),n=(new Date).getFullYear();
$.each(a,function(a,c){"both"==b&&("Entire home/apt"==baketrix.listings[c].room_type?f++:g++);p&&(a=parseInt(baketrix.listings[c].last_review.substring(0,4)),null==baketrix.listings[c].last_review||""==baketrix.listings[c].last_review||a!=n&&a!=n-1||l++);q&&0<getAvail(baketrix.listings[c])&&m++})}updateResultText(Object.keys(a).length+" results (#"+(d-Object.keys(a).length)+" filtered out)",f,g,l,m)}else"none"!==c&&(c=baketrix.areas[c],e=""+("<tr><td>Avg home \u00a3"+c.entireprice+"/nt</td><td>#"+
c.reviews_per_month_entire+" revs/month</td></tr>"),e+="<tr><td>Avg room \u00a3"+c.roomprice+"/nt</td><td>#"+c.reviews_per_month_room+" revs/month</td></tr>",e+="<tr><td>"+a.length+" results</td><td>("+(d-a.length)+" filtered out)</td></tr>",updateResultText("<table>"+e+"</table>",c.entire,c.room,c.year,c.available));return{entire:f,rooms:g,year:l,available:m,list:a}}}
function generateHeatMap(){populateMlist(!0);$("#map_details").html("");displayBreadcrumb("");mapo.createHeatMap(mlist,baketrix.listings,$("#weight_option").is(":checked"))}
function drawAllAreas(){mapo.clearHeatLayer();clearPolyAreas();$("#cluster_option").is(":checked")||($("#cluster_option").prop("checked",!0),mapo.setCluster($(this).is(":checked")));mlist=[];mapo.clearMarkers();map_method="all";$("#map_details").html("");var a=0;$.each(baketrix.areas,function(b,c){console.log(b+" : "+c.list.length);b=generateAreaPinCluster(b,!1);b.status&&(a+=b.nres)});displayBreadcrumb("Too many pins to list all, Click Highlight buttons to show subset.");updateResultText(a+" results",
baketrix.type.entire.length,baketrix.type.room.length,baketrix.thisyear.length,baketrix.isavailable.length);current_area=null;mapFitBounds(!1)}
function generateAreaPolys(a){a=void 0===a?"howmany":a;$.each(areaPolys,function(b,c){var d=.1;if("howmany"==a)if(baketrix.areas[b]&&baketrix.areas[b].list){d=baketrix.areas[b].list;var e=getMapType();"both"!=e&&(d=d.filter(function(a){return baketrix.type[e].includes(a)}));$("#checkbox_lastbooked").is(":checked")&&(d=d.filter(function(a){return baketrix.thisyear.includes(a)}));d=.1+d.length/1E3*.5}else console.log(" no such area? "+b);else"roomprice"==a?(d=baketrix.areas[b].roomprice,d=d/120*.6):
"entireprice"==a?(d=baketrix.areas[b].entireprice,d=d/250*.6):"reviews_per_month_entire"==a?(d=baketrix.areas[b].reviews_per_month_entire,d=.1+d/2E3*.5):"reviews_per_month_room"==a?(d=baketrix.areas[b].reviews_per_month_room,d=.1+d/500*.5):"room365usage"==a?(d=baketrix.areas[b].roomavailindex,d=.1+d/50*.5):"entire365usage"==a&&(d=baketrix.areas[b].entireavailindex,d=.1+d/50*.5);null!=baketrix.areas[b].poly?mapo.updatePoly(baketrix.areas[b].poly,d):(c=mapo.createPolyArea(c.coords,d,b),baketrix.areas[b].poly=
c)});"howmany"==a?createColorKey(.1,.6,1E3,"red"):"roomprice"==a?createColorGrade(20,120,"red"):"entireprice"==a?createColorGrade(50,250,"red"):"reviews_per_month_entire"==a?createColorGrade(100,2E3,"red"):"reviews_per_month_room"==a?createColorGrade(20,500,"red"):"room365usage"==a?createColorKey(.1,.6,50,"red",!0):"entire365usage"==a&&createColorKey(.1,.6,50,"red",!0)}
function showMarkers(a){console.log(a);"search"==map_method&&(map_method="area");if("area"==map_method||"find"==map_method||"host"==map_method)map_method="area",generateAreaPinCluster(a).status&&mapFitBounds(!1)}
function generateAreaPinCluster(a,b){b=void 0===b?!1:b;var c="all"==$("#map_method").val();if(null==baketrix.areas[a]||current_area==a&&!b)return{status:!1};c||($("#map_details").html(""),mapo.clearMarkers());current_area=a;displayBreadcrumb("<a href='"+showURL+"?area="+Object.keys(baketrix.areas).indexOf(current_area)+"&noi=1' target='_blank'>Area id:"+Object.keys(baketrix.areas).indexOf(current_area)+"</a> Click Highlight buttons to sort room list");a=splitListOnFilters(baketrix.areas[a].list,getMapType(),
a);mlist=c&&null!=mlist?mlist.concat(a.list):a.list;var d=[];$.each(a.list,function(a,b){if(a=createPin(b))d.push(a),c||showMarkerDetails(b)});mapo.createAndAddPins(d,$("#cluster_option").is(":checked"));return{status:!0,nres:d.length}}function clusterPins(a){}
function findProlificHosts(a){a=void 0===a?"entire":a;var b={};$.each(baketrix.hosts,function(c,d){d=d.filter(function(b){return baketrix.type[a].includes(b)});3<d.length&&(null==b[d.length]&&(b[d.length]=[]),b[d.length].push(c))});return b}
function generateHostPins(a){current_area=a.host_id;map_method="host";a=a.host_id;displayBreadcrumb("<a href='"+showURL+"?host="+a+"&noi=1' target='_blank'>Host id:"+a+"</a> Click Last-review date to find in map");mlist=null==baketrix.hosts[a]?baketrix.singlehosts[a]:baketrix.hosts[a];mlist=splitListOnFilters(mlist,getMapType(),"summary").list;$("#map_details").html("");var b=[];$.each(mlist,function(a,d){if(a=createPin(d))b.push(a),showMarkerDetails(d)});mapo.createAndAddPins(b,$("#cluster_option").is(":checked"));
0<Object.keys(mlist).length?mapFitBounds():noResultsMessage(getHostName(a))}function noResultsMessage(a,b){a=void 0===a?null:a;b=void 0===b?null:b;var c="";null!=a&&(c+="host "+a+" ");null!=b&&(c+="area "+b+" ");a=getMapType();b=$("#checkbox_lastbooked").is(":checked")?"this year ":"";c+=" has let no "+a+" "+b+"(change filters)";$("#map_details").html("<div>"+c+"</div>")}function getMapType(){return $("#map_type").val()}
function mapFitBounds(a){a=void 0===a?!1:a;var b=mapo.getZoom();(!a||16>=b)&&mapo.mapFitBounds(a)}function mapFitBound(a){mapo.mapFitBound(a)}
function createPin(a){var b=baketrix.listings[a];if(null==b||null==b.latitude||null==b.longitude)return console.log("no geo: "+b),!1;var c="Entire home/apt"==b.room_type?"255,0,0":"255,237,15",d=getPrice(b.prices);d="Entire home/apt"==b.room_type?d/250:d/100;d=Math.min(d,3);var e=1<b.reviews_per_month?4<b.reviews_per_month?1:.8:.5;return mapo.createPin("pin_"+a,{lat:parseFloat(b.latitude),lng:parseFloat(b.longitude)},b.name,c,d,e)}
function pinClicked(a){a=a.split("_");a=parseInt(a[1]);"all"!=map_method?scrollToMarkerDetails(a):showMarkerDetails(a,!0)}var cityCircle;
function foundAnimation(a){null==cityCircle&&(cityCircle=new google.maps.Circle({strokeColor:"#FF0000",strokeOpacity:.8,strokeWeight:2,fillColor:"#FF0000",fillOpacity:.4,map:map,center:{lat:a.position.lat(),lng:a.position.lng()},radius:10}),$(cityCircle).animate({strokeOpacity:.1,radius:20},{duration:500,step:function(a,c){console.log(c.elem.id+" "+c.prop+": "+a);"radius"==c.prop&&cityCircle.setRadius(a);"strokeOpacity"==c.prop&&cityCircle.setOptions({strokeOpacity:a,fillOpacity:a})},complete:function(a){cityCircle.setMap(null);
cityCircle=null}}))}function closeProlific(){$("#prolific_hosts_container").addClass("hidden");$("#mapoptions").removeClass("hidden")}
function updateResultText(a,b,c,d,e){$("#map_results_hidden").html(a);$('#map_type option[value="entire"]').html("Entire-home ("+b+")");$('#map_type option[value="room"]').html("Rooms ("+c+")");$('#map_type option[value="both"]').html("Both ("+(b+c)+")");$("#map_results_year").html("Reviewed 2019+ (<span class='quantity'>"+d+"</span>)");$("#map_results_avail").html("Available 2020+ (<span class='quantity'>"+e+"</span>)")}
function getHostName(a){return null!=baketrix.hosts[a]&&0<baketrix.hosts[a].length?baketrix.listings[baketrix.hosts[a][0]].host_name:"idk"}function createColorGrade(a,b,c,d){d=void 0===d?!1:d;for(var e=[{value:a,label:a},{value:(a+b)/4*2,label:(a+b)/4*2},{value:(a+b)/4*3,label:(a+b)/4*3},{value:a+b,label:a+b}],f="",g=0;g<e.length;g++)f+="<span style='background-color:"+c+";opacity:"+e[g].value/(a+b)+";padding:0 4px;'>"+e[g].label+(d?"%":"")+"</span>";$("#map_color_key").html(f)}
function createColorKey(a,b,c,d,e){e=void 0===e?!1:e;a=[{value:a,label:.1*c},{value:2*b/4,label:2*c/4},{value:3*b/4,label:3*c/4},{value:b,label:c}];b="";for(c=0;c<a.length;c++)b+="<span style='background-color:"+d+";opacity:"+a[c].value+";padding:0 4px;'>"+a[c].label+(e?"%":"")+"</span>";$("#map_color_key").html(b)}var highlightedRow=null;
function scrollToMarkerDetails(a){null!=highlightedRow&&$(highlightedRow).removeClass("highlighted");a=document.getElementById("list"+a);null!=a&&(a.scrollIntoView(),highlightedRow=a,$(highlightedRow).addClass("highlighted"))}
function highlightMarkerRows(a,b,c,d,e){b=void 0===b?!1:b;c=void 0===c?"blue":c;d=void 0===d?null:d;e=void 0===e?!1:e;null!=d&&2<a.length&&(a=a.length<5*d/4?a.slice(Math.floor(a.length/2),a.length):a.slice(Math.floor(a.length-d),a.length));for(d=0;d<a.length;d++)highlightPinlisting(a[d],b,c,e);mapo.changePinColors(a,c);$("#map_details_scroller").scrollTop(0)}
function highlightPinlisting(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?"blue":c;d=void 0===d?!1:d;var e=document.getElementById("list"+a);if(0==d||""!=baketrix.listings[a][d])$(e).attr("class","row highlight_"+c),b&&$(e).detach().prependTo("#map_details")}function removeHighlights(){$(".highlighted").removeClass("highlighted")}
function generatePinSubset(a,b){for(var c=[],d=[],e=31.25>a.length?Math.floor(a.length/2):Math.floor(a.length-25);e<a.length;e++){var f=a[e];if(null==document.getElementById("list"+a[e])){var g=createPin(f);g&&(showMarkerDetails(f,!1,b,!0),c.push(f),d.push(g))}else highlightPinlisting(f,!0,b),c.push(f)}mapo.createAndAddPins(d,!1);mapo.changePinColors(c,b);$("#map_details_scroller").scrollTop(0)}
function showMostBedrooms(){populateMlist();var a=mlist;a.sort(function(a,c){return""==baketrix.listings[a].beds&&""==baketrix.listings[c].beds?0:""==baketrix.listings[a].beds?-1:""==baketrix.listings[c].beds?1:baketrix.listings[a].beds-baketrix.listings[c].beds});null==current_area&&"all"==map_method||"heat"==map_method||"area"==map_method?generatePinSubset(a,"blue"):highlightMarkerRows(a,!0,"blue",25,"beds")}
function showMostExpensive(){populateMlist();var a=$("#checkbox_available_fringe").is(":checked"),b=a?"aug_avg_price":"price",c=mlist;c.sort(function(b,c){b=getPrice(baketrix.listings[b].prices,a);c=getPrice(baketrix.listings[c].prices,a);return""==b&&""==c||-1==b&&-1==c?0:""==b||-1==b?-1:""==c||-1==c?1:b-c});null==current_area&&"all"==map_method||"heat"==map_method||"area"==map_method?generatePinSubset(c,"pink"):highlightMarkerRows(c,!0,"pink",25,b)}
function showMostPopular(){populateMlist();var a=$("#checkbox_available_fringe").is(":checked")?"aug_reviews":"reviews_per_month",b=mlist;b.sort(function(b,d){return""==baketrix.listings[b][a]&&""==baketrix.listings[d][a]?0:""==baketrix.listings[b][a]?-1:""==baketrix.listings[d][a]?1:baketrix.listings[b][a]-baketrix.listings[d][a]});null==current_area&&"all"==map_method||"heat"==map_method||"area"==map_method?generatePinSubset(b,"orange"):highlightMarkerRows(b,!0,"orange",25,a)}
function showMarkerDetails(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?null:c;d=void 0===d?!1:d;var e=baketrix.listings[a];e.id=a;var f=$("#map_details");b&&f.html("");b=$("#checkbox_available_fringe").is(":checked");c=$("<div class='row "+(null!=c?"highlight_"+c:"")+"' id='list"+a+"'></div>");c.append("<div class='col-3'><a href='https://www.airbnb.co.uk/rooms/"+a+"/business-details' target='_blank'>"+e.name+"</a></div>");c.append("<div class='col-1 host_name clickable' title='Show hosts other properties'>"+
e.host_name+" (#"+(null!=baketrix.hosts[e.host_id]?baketrix.hosts[e.host_id].length:1)+")</div>");c.append("<div class='col-1'>"+("Entire home/apt"==e.room_type?"<img src='./images/home-16.png' title='Entire'>":"<img src='./images/bed-16.png' title='Room'>")+"</div>");c.append("<div class='col-1'>"+e.beds+"</div>");if(b){a=Math.floor((getPrice(e.prices,b)-getPrice(e.prices))/getPrice(e.prices)*100);c.append("<div class='col-1'>&pound;"+getPrice(e.prices,b)+"<span class='tiny"+(0<a?"":" pricedown")+
"'>"+a+"%</span></div>");a=getAvail(e.availability,b,"aug");var g=getAvail(e.availability,b);c.append("<div class='col-1'>"+a+"/"+g+" </div>");c.append("<div class='col-1'>#"+e.number_of_reviews+"</div>");c.append("<div class='col-1'>"+e.aug_reviews+"</div>")}else a=getAvail(e.availability,b,"aug")+getAvail(e.availability,b,"roy"),g=getAvail(e.availability,!0)+getAvail(e.availability,!1),c.append("<div class='col-1'>&pound;"+getPrice(e.prices,b)+"</div>"),c.append("<div class='col-1'>"+a+" /"+g+"</div>"),
c.append("<div class='col-1'>#"+e.number_of_reviews+"</div>"),c.append("<div class='col-1'>"+e.reviews_per_month+"</div>");c.append("<div class='col findinmap' title='Find in map'>"+e.last_review+"</div>");d?f.prepend(c):f.append(c)}function displayInfo(a,b){1!=(void 0===b?!1:b)&&$("#loadingModal").modal({})}function isMobileDevice(){return"undefined"!==typeof window.orientation||-1!==navigator.userAgent.indexOf("IEMobile")}
function simulateClick(a){if(mobile){var b=jQuery.Event("touchend",{pageX:50,pageY:50,fake:!0});a.trigger(b)}else a.click()}function getCoord(a,b){return/touch/.test(a.type)?(a.originalEvent||a).changedTouches[0]["page"+b]:a["page"+b]}
function doClick(a,b){if(mobile)a.on("touchstart",function(a){startX=getCoord(a,"X");startY=getCoord(a,"Y");console.log(startX+","+startY)}).on("touchend",function(a){console.log(a);(null!=a.fake||4>Math.abs(getCoord(a,"X")-startX)&&4>Math.abs(getCoord(a,"Y")-startY))&&b.call(this,a)});else a.on("click",b)};
